dubbo:
  application:
    name: bys-commentary-provider
    qos-enable: false
  registry:
    address: 47.101.68.18:22181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20082

spring:
  application:
    name: bys-commentary-provider
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#项目数据库配置（主从）
bys:
  datasource:
    initial-size: 3
    max-active: 20
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    validation-query: SELECT 'x'
    master:
      #      dataSourceKey: mymaster #名字自定义,可在后台日志查看用的哪一个数据库，不声明主库key，默认为连接信息
      url: jdbc:mysql://47.101.68.18:23306/springboot_test?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
    slaves:
      - dataSourceKey: salve1 #从库的key，如果不指定，默认用链接信息
        url: jdbc:mysql://47.101.68.18:23306/springboot_test?characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
      -
        url: jdbc:mysql://47.101.68.18:23306/springboot_test?characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver

