server:
  port: 8090
  servlet:
    context-path: /bys

dubbo:
  application:
    name: bys-web
    qos-enable: false
  registry:
    address: 47.101.68.18:22181
    protocol: zookeeper
  consumer:
    check: false

spring:
  application:
    name: bys-web
  mail:
    host: smtp.qq.com
    username: 578267200@qq.com
    password: iptmssjvhtpqbcaj  #开启 POP3 之后设置的客户端授权密码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true #这地方必须加，不然会授权失败，提示350错误
          starttls:
            enable: true
            required: true
  redis:
    host: 47.101.68.18
    port: 26379
    password: 123456
  session:
    store-type: redis
  thymeleaf:
    cache: false
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  rabbitmq:
    host: 47.101.68.18
    username: guest
    password: guest
  http:
    encoding:
      charset: utf-8 #默认就是utf-8
  data:
    elasticsearch:
      cluster-name: elasticsearch01
      cluster-nodes: 60.205.206.199:9300

  #自定义redis 单位秒
redis:
  host: 47.101.68.18
  port: 26379
  timeout: 3
  password: 123456
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3

logging:
  config: classpath:log4j2.xml
