dubbo:
  application:
    name: bys-artical-provider
    qos-enable: false
  registry:
    address: 47.101.68.18:22181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20081

spring:
  application:
    name: bys-dubbo-remote-provider
#  datasource:
#    name: mysql
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      #基本属性
#      url: jdbc:mysql://47.101.68.18:23306/springboot_test?characterEncoding=utf8&useSSL=false
#      username: root
#      password: 123456
#      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
#      filters: stat, wall
#      driverClassName: com.mysql.jdbc.Driver
#      #配置初始化大小/最小/最大
#      initial-size: 3
#      max-active: 20
#      #最大连接等待超时时间
#      maxWait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#mybatis

#项目数据库配置（主从）
bys:
  datasource:
    initial-size: 3
    max-active: 20
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    validation-query: SELECT 'x'
    master:
      dataSourceKey: mymaster #名字自定义,可在后台日志查看用的哪一个数据库
      url: jdbc:mysql://47.101.68.18:23306/springboot_test?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
#    slaves:
#      - dataSourceKey: salve1 #从库必须配置
#        url: jdbc:mysql://47.101.68.18:23306/springboot_test?characterEncoding=utf8&useSSL=false
#        username: root
#        password: 123456
#        driverClassName: com.mysql.jdbc.Driver
#      - dataSourceKey: salve2
#        url: jdbc:mysql://47.101.68.18:23306/springboot_test?characterEncoding=utf8&useSSL=false
#        username: root
#        password: 123456
#        driverClassName: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapping/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.chong.bys.domain
  #  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #表前缀
    table-prefix: t_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #    capital-mode: true
    #Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    #sql-parser-cache: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    #    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    #jdbc-type-for-null: 'null'
